const P=[
["Contains Duplicate","Arrays & Hashing","E","contains-duplicate","duplicate-integer"],
["Valid Anagram","Arrays & Hashing","E","valid-anagram","is-anagram"],
["Two Sum","Arrays & Hashing","E","two-sum","two-integer-sum"],
["Group Anagrams","Arrays & Hashing","M","group-anagrams","anagram-groups"],
["Top K Frequent Elements","Arrays & Hashing","M","top-k-frequent-elements","top-k-elements-in-list"],
["Product of Array Except Self","Arrays & Hashing","M","product-of-array-except-self","products-of-array-discluding-self"],
["Valid Sudoku","Arrays & Hashing","M","valid-sudoku","valid-sudoku"],
["Longest Consecutive Sequence","Arrays & Hashing","M","longest-consecutive-sequence","longest-consecutive-sequence"],
["Encode and Decode Strings","Arrays & Hashing","M","encode-and-decode-strings","string-encode-and-decode"],
["Valid Palindrome","Two Pointers","E","valid-palindrome","is-palindrome"],
["Two Sum II Input Array Is Sorted","Two Pointers","M","two-sum-ii-input-array-is-sorted","two-integer-sum-ii"],
["3Sum","Two Pointers","M","3sum","three-integer-sum"],
["Container With Most Water","Two Pointers","M","container-with-most-water","max-water-container"],
["Trapping Rain Water","Two Pointers","H","trapping-rain-water","trapping-rain-water"],
["Best Time to Buy and Sell Stock","Sliding Window","E","best-time-to-buy-and-sell-stock","buy-and-sell-crypto"],
["Longest Substring Without Repeating Characters","Sliding Window","M","longest-substring-without-repeating-characters","longest-substring-without-duplicates"],
["Longest Repeating Character Replacement","Sliding Window","M","longest-repeating-character-replacement","longest-repeating-substring-with-replacement"],
["Permutation in String","Sliding Window","M","permutation-in-string","permutation-string"],
["Minimum Window Substring","Sliding Window","H","minimum-window-substring","minimum-window-with-characters"],
["Sliding Window Maximum","Sliding Window","H","sliding-window-maximum","sliding-window-maximum"],
["Valid Parentheses","Stack","E","valid-parentheses","validate-parentheses"],
["Min Stack","Stack","M","min-stack","minimum-stack"],
["Evaluate Reverse Polish Notation","Stack","M","evaluate-reverse-polish-notation","evaluate-reverse-polish-notation"],
["Generate Parentheses","Stack","M","generate-parentheses","generate-parentheses"],
["Daily Temperatures","Stack","M","daily-temperatures","daily-temperatures"],
["Car Fleet","Stack","M","car-fleet","car-fleet"],
["Largest Rectangle in Histogram","Stack","H","largest-rectangle-in-histogram","largest-rectangle-in-histogram"],
["Binary Search","Binary Search","E","binary-search","binary-search"],
["Search a 2D Matrix","Binary Search","M","search-a-2d-matrix","search-2d-matrix"],
["Koko Eating Bananas","Binary Search","M","koko-eating-bananas","eating-bananas"],
["Find Minimum in Rotated Sorted Array","Binary Search","M","find-minimum-in-rotated-sorted-array","find-minimum-in-rotated-sorted-array"],
["Search in Rotated Sorted Array","Binary Search","M","search-in-rotated-sorted-array","find-target-in-rotated-sorted-array"],
["Time Based Key-Value Store","Binary Search","M","time-based-key-value-store","time-based-key-value-store"],
["Median of Two Sorted Arrays","Binary Search","H","median-of-two-sorted-arrays","median-of-two-sorted-arrays"],
["Reverse Linked List","Linked List","E","reverse-linked-list","reverse-a-linked-list"],
["Merge Two Sorted Lists","Linked List","E","merge-two-sorted-lists","merge-two-sorted-linked-lists"],
["Reorder List","Linked List","M","reorder-list","reorder-linked-list"],
["Remove Nth Node From End of List","Linked List","M","remove-nth-node-from-end-of-list","remove-node-from-end-of-linked-list"],
["Copy List with Random Pointer","Linked List","M","copy-list-with-random-pointer","copy-linked-list-with-random-pointer"],
["Add Two Numbers","Linked List","M","add-two-numbers","add-two-numbers"],
["Linked List Cycle","Linked List","E","linked-list-cycle","linked-list-cycle-detection"],
["Find the Duplicate Number","Linked List","M","find-the-duplicate-number","find-duplicate-integer"],
["LRU Cache","Linked List","M","lru-cache","lru-cache"],
["Merge k Sorted Lists","Linked List","H","merge-k-sorted-lists","merge-k-sorted-linked-lists"],
["Reverse Nodes in k-Group","Linked List","H","reverse-nodes-in-k-group","reverse-nodes-in-k-group"],
["Invert Binary Tree","Trees","E","invert-binary-tree","invert-a-binary-tree"],
["Maximum Depth of Binary Tree","Trees","E","maximum-depth-of-binary-tree","depth-of-binary-tree"],
["Diameter of Binary Tree","Trees","E","diameter-of-binary-tree","binary-tree-diameter"],
["Balanced Binary Tree","Trees","E","balanced-binary-tree","balanced-binary-tree"],
["Same Tree","Trees","E","same-tree","same-binary-tree"],
["Subtree of Another Tree","Trees","E","subtree-of-another-tree","subtree-of-a-binary-tree"],
["Lowest Common Ancestor of a Binary Search Tree","Trees","M","lowest-common-ancestor-of-a-binary-search-tree","lowest-common-ancestor-in-binary-search-tree"],
["Binary Tree Level Order Traversal","Trees","M","binary-tree-level-order-traversal","level-order-traversal-of-binary-tree"],
["Binary Tree Right Side View","Trees","M","binary-tree-right-side-view","binary-tree-right-side-view"],
["Count Good Nodes in Binary Tree","Trees","M","count-good-nodes-in-binary-tree","count-good-nodes-in-binary-tree"],
["Validate Binary Search Tree","Trees","M","validate-binary-search-tree","valid-binary-search-tree"],
["Kth Smallest Element in a BST","Trees","M","kth-smallest-element-in-a-bst","kth-smallest-integer-in-bst"],
["Construct Binary Tree from Preorder and Inorder Traversal","Trees","M","construct-binary-tree-from-preorder-and-inorder-traversal","binary-tree-from-preorder-and-inorder-traversal"],
["Binary Tree Maximum Path Sum","Trees","H","binary-tree-maximum-path-sum","binary-tree-maximum-path-sum"],
["Serialize and Deserialize Binary Tree","Trees","H","serialize-and-deserialize-binary-tree","serialize-and-deserialize-binary-tree"],
["Implement Trie Prefix Tree","Tries","M","implement-trie-prefix-tree","implement-prefix-tree"],
["Design Add and Search Words Data Structure","Tries","M","design-add-and-search-words-data-structure","design-word-search-data-structure"],
["Word Search II","Tries","H","word-search-ii","search-for-word-ii"],
["Kth Largest Element in a Stream","Heap / Priority Queue","E","kth-largest-element-in-a-stream","kth-largest-integer-in-a-stream"],
["Last Stone Weight","Heap / Priority Queue","E","last-stone-weight","last-stone-weight"],
["K Closest Points to Origin","Heap / Priority Queue","M","k-closest-points-to-origin","k-closest-points-to-origin"],
["Kth Largest Element in an Array","Heap / Priority Queue","M","kth-largest-element-in-an-array","kth-largest-element-in-an-array"],
["Task Scheduler","Heap / Priority Queue","M","task-scheduler","task-scheduling"],
["Design Twitter","Heap / Priority Queue","M","design-twitter","design-twitter-feed"],
["Find Median from Data Stream","Heap / Priority Queue","H","find-median-from-data-stream","find-median-in-a-data-stream"],
["Subsets","Backtracking","M","subsets","subsets"],
["Combination Sum","Backtracking","M","combination-sum","combination-target-sum"],
["Permutations","Backtracking","M","permutations","permutations"],
["Subsets II","Backtracking","M","subsets-ii","subsets-ii"],
["Combination Sum II","Backtracking","M","combination-sum-ii","combination-target-sum-ii"],
["Word Search","Backtracking","M","word-search","search-for-word"],
["Palindrome Partitioning","Backtracking","M","palindrome-partitioning","palindrome-partitioning"],
["Letter Combinations of a Phone Number","Backtracking","M","letter-combinations-of-a-phone-number","combinations-of-a-phone-number"],
["N-Queens","Backtracking","H","n-queens","n-queens"],
["Number of Islands","Graphs","M","number-of-islands","count-number-of-islands"],
["Max Area of Island","Graphs","M","max-area-of-island","max-area-of-island"],
["Clone Graph","Graphs","M","clone-graph","clone-graph"],
["Islands and Treasure","Graphs","M","walls-and-gates","islands-and-treasure"],
["Rotting Oranges","Graphs","M","rotting-oranges","rotting-fruit"],
["Pacific Atlantic Water Flow","Graphs","M","pacific-atlantic-water-flow","pacific-atlantic-water-flow"],
["Surrounded Regions","Graphs","M","surrounded-regions","surrounded-regions"],
["Course Schedule","Graphs","M","course-schedule","course-schedule"],
["Course Schedule II","Graphs","M","course-schedule-ii","course-schedule-ii"],
["Redundant Connection","Graphs","M","redundant-connection","redundant-connection"],
["Number of Connected Components in an Undirected Graph","Graphs","M","number-of-connected-components-in-an-undirected-graph","count-connected-components"],
["Graph Valid Tree","Graphs","M","graph-valid-tree","valid-tree"],
["Word Ladder","Graphs","H","word-ladder","word-ladder"],
["Reconstruct Itinerary","Advanced Graphs","H","reconstruct-itinerary","reconstruct-flight-path"],
["Min Cost to Connect All Points","Advanced Graphs","M","min-cost-to-connect-all-points","min-cost-to-connect-points"],
["Network Delay Time","Advanced Graphs","M","network-delay-time","network-delay-time"],
["Swim in Rising Water","Advanced Graphs","H","swim-in-rising-water","swim-in-rising-water"],
["Alien Dictionary","Advanced Graphs","H","alien-dictionary","foreign-dictionary"],
["Cheapest Flights Within K Stops","Advanced Graphs","M","cheapest-flights-within-k-stops","cheapest-flight-path"],
["Climbing Stairs","1-D DP","E","climbing-stairs","climbing-stairs"],
["Min Cost Climbing Stairs","1-D DP","E","min-cost-climbing-stairs","min-cost-climbing-stairs"],
["House Robber","1-D DP","M","house-robber","house-robber"],
["House Robber II","1-D DP","M","house-robber-ii","house-robber-ii"],
["Longest Palindromic Substring","1-D DP","M","longest-palindromic-substring","longest-palindromic-substring"],
["Palindromic Substrings","1-D DP","M","palindromic-substrings","palindromic-substrings"],
["Decode Ways","1-D DP","M","decode-ways","decode-ways"],
["Coin Change","1-D DP","M","coin-change","coin-change"],
["Maximum Product Subarray","1-D DP","M","maximum-product-subarray","maximum-product-subarray"],
["Word Break","1-D DP","M","word-break","word-break"],
["Longest Increasing Subsequence","1-D DP","M","longest-increasing-subsequence","longest-increasing-subsequence"],
["Partition Equal Subset Sum","1-D DP","M","partition-equal-subset-sum","partition-equal-subset-sum"],
["Unique Paths","2-D DP","M","unique-paths","count-paths"],
["Longest Common Subsequence","2-D DP","M","longest-common-subsequence","longest-common-subsequence"],
["Best Time to Buy and Sell Stock with Cooldown","2-D DP","M","best-time-to-buy-and-sell-stock-with-cooldown","buy-and-sell-crypto-with-cooldown"],
["Coin Change II","2-D DP","M","coin-change-ii","coin-change-ii"],
["Target Sum","2-D DP","M","target-sum","target-sum"],
["Interleaving String","2-D DP","M","interleaving-string","interleaving-string"],
["Longest Increasing Path in a Matrix","2-D DP","H","longest-increasing-path-in-a-matrix","longest-increasing-path-in-matrix"],
["Distinct Subsequences","2-D DP","H","distinct-subsequences","count-subsequences"],
["Edit Distance","2-D DP","H","edit-distance","edit-distance"],
["Burst Balloons","2-D DP","H","burst-balloons","burst-balloons"],
["Regular Expression Matching","2-D DP","H","regular-expression-matching","regular-expression-matching"],
["Maximum Subarray","Greedy","M","maximum-subarray","maximum-subarray"],
["Jump Game","Greedy","M","jump-game","jump-game"],
["Jump Game II","Greedy","M","jump-game-ii","jump-game-ii"],
["Gas Station","Greedy","M","gas-station","gas-station"],
["Hand of Straights","Greedy","M","hand-of-straights","hand-of-straights"],
["Merge Triplets to Form Target Triplet","Greedy","M","merge-triplets-to-form-target-triplet","merge-triplets-to-form-target"],
["Partition Labels","Greedy","M","partition-labels","partition-labels"],
["Valid Parenthesis String","Greedy","M","valid-parenthesis-string","valid-parenthesis-string"],
["Insert Interval","Intervals","M","insert-interval","insert-new-interval"],
["Merge Intervals","Intervals","M","merge-intervals","merge-intervals"],
["Non-overlapping Intervals","Intervals","M","non-overlapping-intervals","non-overlapping-intervals"],
["Meeting Rooms","Intervals","E","meeting-rooms","meeting-schedule"],
["Meeting Rooms II","Intervals","M","meeting-rooms-ii","meeting-schedule-ii"],
["Minimum Interval to Include Each Query","Intervals","H","minimum-interval-to-include-each-query","minimum-interval-including-query"],
["Rotate Image","Math & Geometry","M","rotate-image","rotate-matrix"],
["Spiral Matrix","Math & Geometry","M","spiral-matrix","spiral-matrix"],
["Set Matrix Zeroes","Math & Geometry","M","set-matrix-zeroes","set-zeroes-in-matrix"],
["Happy Number","Math & Geometry","E","happy-number","non-cyclical-number"],
["Plus One","Math & Geometry","E","plus-one","plus-one"],
["Pow(x, n)","Math & Geometry","M","powx-n","pow-x-n"],
["Multiply Strings","Math & Geometry","M","multiply-strings","multiply-strings"],
["Detect Squares","Math & Geometry","M","detect-squares","count-squares"],
["Single Number","Bit Manipulation","E","single-number","single-number"],
["Number of 1 Bits","Bit Manipulation","E","number-of-1-bits","number-of-one-bits"],
["Counting Bits","Bit Manipulation","E","counting-bits","counting-bits"],
["Reverse Bits","Bit Manipulation","E","reverse-bits","reverse-bits"],
["Missing Number","Bit Manipulation","E","missing-number","missing-number"],
["Sum of Two Integers","Bit Manipulation","M","sum-of-two-integers","sum-of-two-integers"],
["Reverse Integer","Bit Manipulation","M","reverse-integer","reverse-integer"]
];
const BLIND75=new Set(`contains-duplicate valid-anagram two-sum group-anagrams top-k-frequent-elements product-of-array-except-self valid-sudoku encode-and-decode-strings longest-consecutive-sequence valid-parentheses best-time-to-buy-and-sell-stock valid-palindrome longest-substring-without-repeating-characters 3sum container-with-most-water trapping-rain-water binary-search search-a-2d-matrix best-time-to-buy-and-sell-stock reverse-linked-list merge-two-sorted-lists reorder-list remove-nth-node-from-end-of-list linked-list-cycle invert-binary-tree maximum-depth-of-binary-tree same-tree lowest-common-ancestor-of-a-binary-search-tree binary-tree-level-order-traversal validate-binary-search-tree kth-smallest-element-in-a-bst serialize-and-deserialize-binary-tree number-of-islands clone-graph max-area-of-island pacific-atlantic-water-flow course-schedule graph-valid-tree longest-consecutive-sequence longest-palindromic-substring palindromic-substrings climbing-stairs coin-change house-robber maximum-product-subarray word-break combination-sum word-search subsets permutations maximum-subarray jump-game jump-game-ii insert-interval merge-intervals non-overlapping-intervals meeting-rooms meeting-rooms-ii rotate-image spiral-matrix set-matrix-zeroes happy-number missing-number counting-bits sum-of-two-integers`.split(" "));
const EXTRA=[
  ["Find the Difference","Arrays & Hashing","E","find-the-difference"],["Longest Common Prefix","Arrays & Hashing","E","longest-common-prefix"],["Majority Element","Arrays & Hashing","E","majority-element"],["Sort Colors","Two Pointers","M","sort-colors"],["3Sum Closest","Two Pointers","M","3sum-closest"],["Longest Repeating Character Replacement","Sliding Window","M","longest-repeating-character-replacement"],["Asteroid Collision","Stack","M","asteroid-collision"],["Decode String","Stack","M","decode-string"],["Next Greater Element I","Stack","E","next-greater-element-i"],["Pow(x, n)","Binary Search","M","powx-n"],["Find Peak Element","Binary Search","M","find-peak-element"],["Intersection of Two Linked Lists","Linked List","E","intersection-of-two-linked-lists"],["Palindrome Linked List","Linked List","E","palindrome-linked-list"],["Design Linked List","Linked List","M","design-linked-list"],["Binary Tree Zigzag Level Order Traversal","Trees","M","binary-tree-zigzag-level-order-traversal"],["Path Sum","Trees","E","path-sum"],["Serialize and Deserialize BST","Trees","M","serialize-and-deserialize-bst"],["Implement Trie","Tries","M","implement-trie-prefix-tree"],["Kth Largest Element in a Stream","Heap / Priority Queue","E","kth-largest-element-in-a-stream"],["Reorganize String","Heap / Priority Queue","M","reorganize-string"],["Combination Sum III","Backtracking","M","combination-sum-iii"],["Sudoku Solver","Backtracking","H","sudoku-solver"],["Open the Lock","Graphs","M","open-the-lock"],["Accounts Merge","Advanced Graphs","M","accounts-merge"],["Number of Ways to Arrive at Destination","Advanced Graphs","M","number-of-ways-to-arrive-at-destination"],["Longest Common Subsequence","2-D DP","M","longest-common-subsequence"],["Decode Ways","1-D DP","M","decode-ways"],["Perfect Squares","1-D DP","M","perfect-squares"],["Triangle","2-D DP","M","triangle"],["Maximal Square","2-D DP","M","maximal-square"],["Maximum Subarray Sum with One Deletion","Greedy","M","maximum-subarray-sum-with-one-deletion"],["Candy","Greedy","H","candy"],["Interval List Intersections","Intervals","M","interval-list-intersections"],["Employee Free Time","Intervals","H","employee-free-time"],["Gas Station","Greedy","M","gas-station"],["Roman to Integer","Math & Geometry","E","roman-to-integer"],["String to Integer (atoi)","Math & Geometry","M","string-to-integer-atoi"],["Multiply Strings","Math & Geometry","M","multiply-strings"],["Power of Two","Bit Manipulation","E","power-of-two"],["Bitwise AND of Numbers Range","Bit Manipulation","M","bitwise-and-of-numbers-range"]
];
const MORE=[
  ["Subarray Sum Equals K","Arrays & Hashing","M","subarray-sum-equals-k"],["Longest Consecutive Sequence II","Arrays & Hashing","M","longest-consecutive-sequence-ii"],["Find All Numbers Disappeared in an Array","Arrays & Hashing","E","find-all-numbers-disappeared-in-an-array"],["Minimum Size Subarray Sum","Sliding Window","M","minimum-size-subarray-sum"],["Substring with Concatenation of All Words","Sliding Window","H","substring-with-concatenation-of-all-words"],["Basic Calculator","Stack","H","basic-calculator"],["Remove K Digits","Stack","M","remove-k-digits"],["Online Stock Span","Stack","M","online-stock-span"],["Search in Rotated Sorted Array II","Binary Search","M","search-in-rotated-sorted-array-ii"],["Random Pick with Weight","Binary Search","M","random-pick-with-weight"],["Add Two Numbers II","Linked List","M","add-two-numbers-ii"],["Flatten a Multilevel Doubly Linked List","Linked List","M","flatten-a-multilevel-doubly-linked-list"],["Design Circular Queue","Linked List","M","design-circular-queue"],["Populating Next Right Pointers in Each Node","Trees","M","populating-next-right-pointers-in-each-node"],["Binary Tree Paths","Trees","E","binary-tree-paths"],["Find Duplicate Subtrees","Trees","M","find-duplicate-subtrees"],["Word Search III","Tries","H","word-search-iii"],["Top K Frequent Words","Heap / Priority Queue","M","top-k-frequent-words"],["Find K Pairs with Smallest Sums","Heap / Priority Queue","M","find-k-pairs-with-smallest-sums"],["Sliding Window Median","Heap / Priority Queue","H","sliding-window-median"],["Restore IP Addresses","Backtracking","M","restore-ip-addresses"],["Partition to K Equal Sum Subsets","Backtracking","M","partition-to-k-equal-sum-subsets"],["Graph Valid Tree II","Graphs","M","graph-valid-tree-ii"],["Evaluate Division","Graphs","M","evaluate-division"],["Snakes and Ladders","Graphs","M","snakes-and-ladders"],["Dijkstra Shortest Path","Advanced Graphs","M","network-delay-time"],["Critical Connections in a Network","Advanced Graphs","H","critical-connections-in-a-network"],["Reorder Routes to Make All Paths Lead to the City Zero","Advanced Graphs","M","reorder-routes-to-make-all-paths-lead-to-the-city-zero"],["Delete and Earn","1-D DP","M","delete-and-earn"],["Paint House","1-D DP","M","paint-house"],["Minimum Path Sum","2-D DP","M","minimum-path-sum"],["Dungeon Game","2-D DP","H","dungeon-game"],["House Robber III","2-D DP","M","house-robber-iii"],["Maximum Length of Repeated Subarray","2-D DP","M","maximum-length-of-repeated-subarray"],["Wiggle Subsequence","Greedy","M","wiggle-subsequence"],["Queue Reconstruction by Height","Greedy","M","queue-reconstruction-by-height"],["Minimum Number of Arrows to Burst Balloons","Intervals","M","minimum-number-of-arrows-to-burst-balloons"],["Data Stream as Disjoint Intervals","Intervals","H","data-stream-as-disjoint-intervals"],["Valid Number","Math & Geometry","H","valid-number"],["Integer to Roman","Math & Geometry","M","integer-to-roman"],["Sqrt(x)","Math & Geometry","E","sqrtx"],["Excel Sheet Column Number","Math & Geometry","E","excel-sheet-column-number"],["Reverse Linked List II","Linked List","M","reverse-linked-list-ii"],["Rotate List","Linked List","M","rotate-list"],["Binary Tree Inorder Traversal","Trees","E","binary-tree-inorder-traversal"],["Binary Tree Preorder Traversal","Trees","E","binary-tree-preorder-traversal"],["Binary Tree Postorder Traversal","Trees","E","binary-tree-postorder-traversal"],["Symmetric Tree","Trees","E","symmetric-tree"],["Minimum Depth of Binary Tree","Trees","E","minimum-depth-of-binary-tree"],["Course Schedule III","Advanced Graphs","H","course-schedule-iii"],["Fibonacci Number","1-D DP","E","fibonacci-number"],["Climbing Stairs with Cost","1-D DP","E","min-cost-climbing-stairs"],["Combination Sum IV","1-D DP","M","combination-sum-iv"],["House Robber IV","1-D DP","M","house-robber-iv"],["Minimum Falling Path Sum","2-D DP","M","minimum-falling-path-sum"],["Triangle Minimum Path","2-D DP","M","triangle"],["Jump Game VII","Greedy","M","jump-game-vii"],["Partition Array for Maximum Sum","Greedy","M","partition-array-for-maximum-sum"],["Interval Scheduling","Intervals","M","interval-scheduling"],["Number Complement","Bit Manipulation","E","number-complement"],["Reverse Bits II","Bit Manipulation","E","reverse-bits"]
];
const SETS={
  blind75:{label:"Blind 75",description:"The classic interview essentials, sharpened one review at a time.",problems:P.filter(p=>BLIND75.has(p[3])).concat(EXTRA.slice(0,14))},
  neetcode150:{label:"NeetCode 150",description:"The complete pattern-first roadmap, ready when you are.",problems:P},
  neetcode250:{label:"NeetCode 250",description:"A deeper library of patterns for a more thorough interview prep cycle.",problems:P.concat(EXTRA,MORE.slice(0,60))}
};

export { SETS };
